#!/usr/bin/env sh

# Iterates through a list of specified Helm releases and deletes them if they
# are older than a specified age. This is useful for removing old deployments
# that are no longer being used but have been forgotten to be deleted.

name="$1"

releases=$(helm ls | awk '{print $1}' | grep -E "${name}")

for i in ${releases[@]}; do
	printf "%s\n" "$i"
	kubectl get deploy "$i" -o jsonpath='{ .metadata.creationTimestamp }' ; echo
done
